spring:
  application:
    name: sws
  datasource:
    url: jdbc:postgresql://localhost:5432/skfdb # should be kept as an environment variable
    username: user # should be kept as an environment variable
    password: pass123 # should be kept as an environment variable
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    context-path: /skf
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

server:
  servlet:
    context-path: /skf

# mocked service in docker
digikat:
  url: http://localhost:8081

file:
  upload-dir: uploads
