spring:
  application:
    name: sws
  datasource:
    url: jdbc:postgresql://localhost:5432/skfdb # should be kept as an environment variable
    username: user # should be kept as an environment variable
    password: pass123 # should be kept as an environment variable
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

digikat:
  url: http://localhost:8081